export const voicePage=`<h1>声音</h1><p>选择一套声音试听，满意后保存用于聊天。日语发声时，中文字幕随声音出现。</p>
<style>.voice-options{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}.voice-option{border:1px solid #d9e4f1;border-radius:12px;padding:14px}.voice-option[data-selected="true"]{border-color:#7196c7;background:#f2f7fe}.voice-option strong{display:block}.voice-option p{margin:7px 0;font-size:13px}.voice-option button{font-size:13px;padding:7px 12px;margin-top:8px}.voice-state{font-size:13px;color:#527298}.voice-option:first-child{grid-column:1/-1}select{box-sizing:border-box;width:100%;font:inherit;padding:11px 13px;border:1px solid #c9d8ec;border-radius:11px;color:#334968;background:#fbfdff}details{margin:22px 0}summary{cursor:pointer;color:#527298}#voice-audio{width:100%;margin-top:10px}#voice-status{white-space:pre-wrap}@media(max-width:520px){.voice-options{grid-template-columns:1fr}}</style>
<div id="voice-options" class="voice-options" aria-label="声音方案"></div><button id="voice-refresh" type="button" class="secondary">刷新准备状态</button>
<form id="voice-form"><label for="voice-engine">当前选择</label><select id="voice-engine"></select><p id="voice-engine-note"></p>
<label><input id="voice-enabled" type="checkbox" style="width:auto"> 朗读聊天回复</label><label><input id="voice-japaneseSubtitles" type="checkbox" style="width:auto"> 日语发声／中文字幕</label>
<label for="voice-speed">语速</label><input id="voice-speed" type="number" min="0.5" max="2" step="0.05"><p>1.0 为标准语速，0.85 较舒缓。Fish 会根据逗号、句号等标点补充停顿提示，仍以整段音频连续播放。</p>
<div id="voice-fish-expression" hidden><label for="voice-fishExpression">说话语气</label><select id="voice-fishExpression"><option value="natural">原版语气</option><option value="warm">亲近一点 · 温柔有起伏</option><option value="lively">活泼一点 · 更有精神</option></select><p>选择后可生成试听，满意再保存。不同语气可能影响音色与停顿。</p></div>
<details id="voice-reference-settings"><summary>现有 GPT-SoVITS 的参考音频与接口</summary><label for="voice-endpoint">本机声音接口</label><input id="voice-endpoint"><label for="voice-referenceAudio">参考音频路径（3～10 秒）</label><input id="voice-referenceAudio"><label for="voice-promptText">参考音频对应原文</label><textarea id="voice-promptText" rows="3"></textarea><label for="voice-promptLanguage">参考音频语言</label><select id="voice-promptLanguage"><option value="ja">日语</option><option value="zh">中文</option><option value="en">英语</option><option value="ko">韩语</option><option value="yue">粤语</option></select><label for="voice-textLanguage">回复朗读语言</label><select id="voice-textLanguage"><option value="auto">自动识别</option><option value="ja">日语</option><option value="zh">中文</option><option value="en">英语</option><option value="ko">韩语</option><option value="yue">粤语</option></select></details>
<button id="voice-save">保存为聊天声音</button><label for="voice-testText">统一试听文本（日语）</label><textarea id="voice-testText" rows="2" maxlength="300">先生、おかえりなさい。アリスは待っていました。</textarea><button id="voice-test" class="secondary" type="button">生成试听</button><button id="voice-cancel" class="secondary" type="button" hidden>取消试听</button><p id="voice-status" role="status"></p><audio id="voice-audio" controls></audio></form>`;

export const voiceScript=`
const voiceKeys=['endpoint','referenceAudio','promptText','promptLanguage','textLanguage','speed','fishExpression'];let voiceRevision,voiceAudioUrl,voiceEngineList=[],voiceLoaded=false,voiceTesting=false,voiceSaving=false,voiceController;
function voiceBody(){return {engine:get('voice-engine').value,enabled:get('voice-enabled').checked,japaneseSubtitles:get('voice-japaneseSubtitles').checked,...Object.fromEntries(voiceKeys.map(k=>[k,k==='speed'?Number(get('voice-'+k).value):get('voice-'+k).value]))};}
async function voiceApi(path,method='GET',body,signal){const r=await fetch(path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal});if(!r.ok){const e=await r.json();throw Error(e.error);}return r;}
function voiceSelection(){const id=get('voice-engine').value,p=voiceEngineList.find(e=>e.id===id);for(const card of get('voice-options').children)card.dataset.selected=String(card.dataset.engine===id);get('voice-engine-note').textContent=p?(p.description+' · '+p.mode+' · '+p.status+(p.metrics?'；首段音频约 '+(p.metrics.tts_first_audio_ms/1000).toFixed(2)+' 秒，整句约 '+(p.metrics.tts_complete_ms/1000).toFixed(2)+' 秒（仅合成耗时）':'')):'';get('voice-reference-settings').hidden=id!=='gpt-sovits';get('voice-fish-expression').hidden=!['fish','fish-finetuned'].includes(id);get('voice-engine').disabled=voiceSaving||voiceTesting;get('voice-test').disabled=voiceSaving||voiceTesting||!p?.ready||!voiceLoaded;get('voice-save').disabled=voiceSaving||voiceTesting||!p?.ready||!voiceLoaded;}
async function refreshVoiceEngines(){try{const {engines}=await(await voiceApi('/api/voice/engines')).json();if(JSON.stringify(engines)===JSON.stringify(voiceEngineList))return;voiceEngineList=engines;const selected=get('voice-engine').value;get('voice-engine').replaceChildren();get('voice-options').replaceChildren();for(const p of engines){const option=document.createElement('option');option.value=p.id;option.textContent=p.name+(p.ready?'':'（'+p.status+'）');get('voice-engine').append(option);const card=document.createElement('div');card.className='voice-option';card.dataset.engine=p.id;const title=document.createElement('strong');title.textContent=p.name;const desc=document.createElement('p');desc.textContent=p.description;const status=document.createElement('div');status.className='voice-state';status.textContent=p.mode+' · '+p.status;const choose=document.createElement('button');choose.type='button';choose.className='secondary';choose.textContent=p.ready?'选用试听':'查看进度';choose.onclick=()=>{if(voiceSaving||voiceTesting)return;get('voice-engine').value=p.id;voiceSelection();};card.append(title,desc,status,choose);if(p.ready&&p.id!=='gpt-sovits'){const play=document.createElement('button');play.type='button';play.className='secondary';play.textContent='播放对比样本';play.onclick=()=>playVoiceSample(p);card.append(play);}get('voice-options').append(card);}if(engines.some(e=>e.id===selected))get('voice-engine').value=selected;voiceSelection();}catch(e){get('voice-status').textContent=e.message;}}
async function playVoiceSample(p){if(voiceSaving||voiceTesting)return;try{get('voice-audio').pause();const r=await voiceApi('/api/voice/samples/'+p.id);const blob=await r.blob();if(voiceAudioUrl)URL.revokeObjectURL(voiceAudioUrl);voiceAudioUrl=URL.createObjectURL(blob);get('voice-audio').src=voiceAudioUrl;get('voice-status').textContent=p.name+' · 统一对比样本；聊天声音未改变。';await get('voice-audio').play();}catch(e){get('voice-status').textContent=e.message;}}
get('voice-engine').onchange=voiceSelection;get('voice-refresh').onclick=refreshVoiceEngines;
Promise.all([voiceApi('/api/voice').then(r=>r.json()),refreshVoiceEngines()]).then(([{profile:p}])=>{voiceRevision=p.revision;get('voice-engine').value=p.engine;get('voice-enabled').checked=p.enabled;get('voice-japaneseSubtitles').checked=p.japaneseSubtitles;voiceKeys.forEach(k=>get('voice-'+k).value=p[k]);voiceLoaded=true;voiceSelection();get('voice-status').textContent='当前聊天声音已读取。';}).catch(e=>{get('voice-status').textContent=e.message;get('voice-save').disabled=true;});
setInterval(()=>{if(!document.hidden&&!get('settings-voice').hidden&&!voiceTesting)void refreshVoiceEngines();},5000);
get('voice-form').onsubmit=async e=>{e.preventDefault();if(voiceSaving||voiceTesting)return;voiceSaving=true;voiceSelection();get('voice-status').textContent='正在保存…';try{const r=await voiceApi('/api/voice','PUT',{...voiceBody(),expectedRevision:voiceRevision});const {profile:p}=await r.json();voiceRevision=p.revision;get('voice-status').textContent='已保存，下一条聊天使用这套声音。首次使用新模型需要稍等。';}catch(e){get('voice-status').textContent=e.message;}finally{voiceSaving=false;voiceSelection();}};
get('voice-test').onclick=async()=>{if(voiceSaving||voiceTesting)return;voiceTesting=true;voiceSelection();get('voice-cancel').hidden=false;get('voice-audio').pause();get('voice-status').textContent='正在生成试听，首次切换需要加载模型…';voiceController=new AbortController();const began=performance.now();try{const r=await voiceApi('/api/voice/test','POST',{...voiceBody(),text:get('voice-testText').value},voiceController.signal);const blob=await r.blob();if(voiceAudioUrl)URL.revokeObjectURL(voiceAudioUrl);voiceAudioUrl=URL.createObjectURL(blob);get('voice-audio').src=voiceAudioUrl;const ms=Number(r.headers.get('X-Voice-Generation-Ms'))||performance.now()-began;get('voice-status').textContent='试听已生成，用时 '+(ms/1000).toFixed(2)+' 秒（包含首次模型加载；聊天等待时间还包含回复生成）。';try{await get('voice-audio').play();}catch{}}catch(e){get('voice-status').textContent=e.name==='AbortError'?'已取消试听。':e.message;}finally{voiceTesting=false;get('voice-cancel').hidden=true;voiceSelection();}};
get('voice-cancel').onclick=()=>{voiceController?.abort();get('voice-audio').pause();};
`;
